# Server Configuration
server:
  port: 10101
  servlet:
    context-path: /camunda-ocr

# Spring Configurations
spring:
  application:
    name: camunda-ocr
  datasource:
    url: jdbc:h2:file:./camunda-ocr-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      minimumIdle: 5
      maximumPoolSize: 50
      connectionTimeout: 2000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-update
        jdbc:
          lob:
            non_contextual_creation: false
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 1MB
      max-request-size: 1MB

# Camunda Configuration
camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    metrics:
      db-reporter-activate: false
    database:
      schema-update: drop-create

# OCR Space
ocr-space:
  key: <add your key here>
  base-url: https://api.ocr.space
  post-url: ${ocr-space.base-url}/parse/image
